version: '3.7'

services:
  db:
    container_name: db
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /opt/polymesh-postgres:/var/lib/postgresql/data
    ports:
      - '15432:5432'